version: '3.8'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - '80:80'
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d/
            - ./mainset/public:/var/www/public
        depends_on:
            - php-fpm
            - postgres
        networks:
            - app-network

    php-fpm:
        build:
            context: docker
            dockerfile: docker/docker/php-fpm/Dockerfile
        container_name: php-fpm
        working_dir: /var/www
        volumes:
            - ./mainset:/var/www/
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
        networks:
            - app-network

    postgres:
        image: postgres:latest
        container_name: pg-data
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER:  ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - pg-data:/var/lib/postgresql/data
        networks:
            - app-network

    workspace:
        build:
            context: docker
            dockerfile: docker/docker/workspace/Dockerfile
        container_name: workspace
        volumes:
            - ./mainset:/var/www
        working_dir: /var/www
        depends_on:
            -  postgres
        networks:
            - app-network

volumes:
    pg-data:
networks:
    app-network:
        driver: bridge